/**
 * DO NOT EDIT THIS FILE.
 * See the following change record for more information,
 * https://www.drupal.org/node/2815083
 *
**/

(function($, Drupal, drupalSettings) {

  'use strict';

  Drupal.behaviors.mybehavior = {
    attach: function(context, settings) {
      $('.cart-block--summary__count').each(function(){
        var text =  $(this).text().substring(0, 2);
        $(this).html(text);
      })
    }
  };

  $(document).ready(function() {


    /**
     *  Search Placeholder
    */
    $(".search-area .form-search").attr("placeholder", "Type search...");

    /**
     *  Mobile Icon
     */
    $('.mob-icon').on('click', function(e) {
      if (($('body').hasClass('is-search-active'))) {
        $('body').removeClass("is-search-active");
      }
      $('body').toggleClass("is-menu-active");
    });

    /**
     *  Search Icon
     */
    $('.search-icon').on('click', function(e) {
      if (($('body').hasClass('is-menu-active'))) {
        $('body').removeClass("is-menu-active");
      }
      $('body').toggleClass("is-search-active");
    });

    /**
     *  Silder
     */
    $('.slides').slick({
      dots: false,
      infinite: true,
      autoplaySpeed: 2000,
      slidesToShow: 1,
      adaptiveHeight: true,
      arrows: true,
      autoplay: true
    });

    /**
     * Slider
     */
    $('.slider ul li img').each(function() {
      var imageUrl = $(this).attr('src');
      var t = $(this).parent().css('background-image', 'url(' + imageUrl + ')');
    })

    /*
    ** Main menu
    */
    if ($(window).width() < 767) {
      $('.menu--main .menu-item--expanded > ul').hide();
      $('.menu--main .menu-item--expanded > a').on('click', function(e) {
        e.preventDefault();
        $('.menu--main .menu-item--expanded > a').not(this).next().slideUp();
        $(this).next().slideToggle();
        $('.menu--main .menu-item--expanded > a').not(this).parent().removeClass('menu-active');
        $(this).parent().toggleClass('menu-active');
      });
    }
    $(window).resize(function() {
      if ($(window).width() > 768) {
        $('.menu--main .menu-item--expanded > ul').show();
      }
      if ($(window).width() < 767) {
        $('.menu--main .menu-item--expanded > ul').hide();
      }
    });
  });
  
})(jQuery, Drupal, drupalSettings);
  